2022-07-30 11:13:50,008 - [custom_log.py --> line:61] - INFO : case_name:get_cmdopts
2022-07-30 11:13:50,008 - [custom_log.py --> line:62] - INFO : 
method:post
url:http://127.0.0.1/WoniuSales_20180508_V1.4_bin/user/login
data:{'username': 'lm', 'password': 'LiuM123', 'verifycode': '0000'}
headers:None
host:None
2022-07-30 11:13:52,041 - [custom_log.py --> line:66] - ERROR : HTTPConnectionPool(host='127.0.0.1', port=80): Max retries exceeded with url: /WoniuSales_20180508_V1.4_bin/user/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023B545A1420>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2022-07-30 11:13:52,044 - [custom_log.py --> line:61] - INFO : case_name:get_cmdopts
2022-07-30 11:13:52,044 - [custom_log.py --> line:62] - INFO : 
method:post
url:http://127.0.0.1/WoniuSales_20180508_V1.4_bin/user/login
data:{'username': 'liuchan', 'password': 'LiuC456', 'verifycode': '0000'}
headers:None
host:None
2022-07-30 11:13:54,090 - [custom_log.py --> line:66] - ERROR : HTTPConnectionPool(host='127.0.0.1', port=80): Max retries exceeded with url: /WoniuSales_20180508_V1.4_bin/user/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023B545A1690>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2022-07-30 11:13:54,090 - [custom_log.py --> line:61] - INFO : case_name:get_cmdopts
2022-07-30 11:13:54,090 - [custom_log.py --> line:62] - INFO : 
method:post
url:http://127.0.0.1/WoniuSales_20180508_V1.4_bin/user/login
data:{'username': 'dy', 'password': 'DY123', 'verifycode': '0000'}
headers:None
host:None
2022-07-30 11:13:56,154 - [custom_log.py --> line:66] - ERROR : HTTPConnectionPool(host='127.0.0.1', port=80): Max retries exceeded with url: /WoniuSales_20180508_V1.4_bin/user/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023B5457A5C0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2022-07-30 11:13:56,156 - [custom_log.py --> line:61] - INFO : case_name:get_cmdopts
2022-07-30 11:13:56,156 - [custom_log.py --> line:62] - INFO : 
method:post
url:http://127.0.0.1/WoniuSales_20180508_V1.4_bin/user/login
data:{'username': 'wangwu', 'password': 'ww123', 'verifycode': '0000'}
headers:None
host:None
2022-07-30 11:13:58,209 - [custom_log.py --> line:66] - ERROR : HTTPConnectionPool(host='127.0.0.1', port=80): Max retries exceeded with url: /WoniuSales_20180508_V1.4_bin/user/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023B5457BAC0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2022-07-30 11:13:58,211 - [custom_log.py --> line:61] - INFO : case_name:get_cmdopts
2022-07-30 11:13:58,211 - [custom_log.py --> line:62] - INFO : 
method:post
url:http://127.0.0.1/WoniuSales_20180508_V1.4_bin/user/login
data:{'username': 'admin', 'password': 'Milor123', 'verifycode': '0000'}
headers:None
host:None
2022-07-30 11:14:00,255 - [custom_log.py --> line:66] - ERROR : HTTPConnectionPool(host='127.0.0.1', port=80): Max retries exceeded with url: /WoniuSales_20180508_V1.4_bin/user/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023B5457B190>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
